name: "Podcast Generator"
author: "Nam Nguyen"
description: "A GitHub Action to generate podcast feed from a YAML file."
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email: 
    description: "Email address for the podcast feed."
    required: true
    default: "${{ github.actor }}@localhost"
  name:
    description: "Name of the podcast."
    required: true
    default: "{{ github.actor }}"